name: Build Conda

on:
  pull_request:
jobs:
  build-conda:
    runs-on: ubuntu-latest
    name: "Build: Conda"
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "name=RELEASE_VERSION" >> $GITHUB_ENV
      - name: build-with-conda
        uses: jegp/conda-package-publish-action@master
        with:
          subDir: "publish/conda"
          platforms: "win osx linux"
